version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  Install:
  BeforeInstall:
    - location: scripts/install.sh
      timeout: 300
      runas: root
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  AfterInstall: